# Generated by Django 5.2.6 on 2025-09-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_patience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no_patience.doctor')),
            ],
        ),
    ]
