# Generated by Django 5.2.6 on 2026-02-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_patience', '0003_botmessage_chat_usermessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('my_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no_patience.chat')),
            ],
        ),
        migrations.DeleteModel(
            name='BotMessage',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
