# Generated by Django 5.2.6 on 2026-02-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_patience', '0004_message_delete_botmessage_delete_usermessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='BotMessage',
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('my_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no_patience.chat')),
            ],
        ),
    ]
