# Generated by Django 5.2.6 on 2026-02-24 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_patience', '0005_rename_message_botmessage_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
