# Generated by Django 5.2.6 on 2026-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_patience', '0007_remove_usermessage_my_chat_message_delete_botmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
